# ------------------------------------------------------------------------------------------
cirrus_freebsd_clang_test_task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64
    # freebsd-11-2-release-amd64
  env:
    CONAN_GCC_VERSIONS: 9
    CONAN_REFERENCE: "icu/65.1"
    CONAN_USERNAME: "kth"
    CONAN_LOGIN_USERNAME: "fpelliccioni"
    CONAN_CHANNEL: "stable"
    CONAN_UPLOAD: "https://api.bintray.com/conan/k-nuth/kth"
    CONAN_STABLE_BRANCH_PATTERN: "release/*"
    CONAN_LOGIN_USERNAME: ENCRYPTED[!0fc5affed4d2084389c1cb0cfa369767e679a054d8e418dcf98c4d25d34b6bec6a5e3dd0235f3dd66686c1739d7bfbcc!]
    CONAN_PASSWORD: ENCRYPTED[!3ed4d8bb7c72f35dc679f44fa521616f928c7286fa0d84195c3b1cd7c058e0154085f9b8dd8e57268c4e7a343eb34a18!]
    # matrix:
    #   STDFLAG: -std=c++14
    #   STDFLAG: -std=c++17
    #   #STDFLAG: -std=c++2a
  # install_script: pkg install -y gmake
  # version_script: gmake --version && gmake -C test showcxxversion
  # test_script: cd test && gmake -j4 && gmake test

  install_script:
    # - wget https://bootstrap.pypa.io/get-pip.py 
    # - python get-pip.py 
    # - chmod +x .travis/install.sh 
    # - chmod +x .travis/run.sh 
    # - ./.travis/install.sh

    # - set -e
    # - set -x

    - freebsd-version
    - which python
    # - ln -s /usr/local/bin/python3.6 /usr/local/bin/python
    - python --version
    - pkg install -y py36-pip
    - which pip-3.6
    - pip install --upgrade pip

    - pip install conan --upgrade
    - pip install conan_package_tools
    - pip install cpuid --upgrade
    - conan user

  build_script:
    # - ./.travis/run.sh
    python build.py






# ------------------------------------------------------------------------------------------
# cirrus_gcc_test_task:
#   only_if: &default-condition $CIRRUS_BRANCH == 'master' || $CIRRUS_BRANCH == 'dev' || $CIRRUS_BRANCH =~ 'feature-.*' || $CIRRUS_BRANCH =~ 'feature_.*' || $CIRRUS_BRANCH =~ 'cirrusci/.*' || $CIRRUS_BASE_BRANCH != ''
#   auto_cancellation: true
#   container:
#     image: gcc:latest
#   # env:
#   #   matrix:
#   #     STDFLAG: -std=c++14
#   #     STDFLAG: -std=c++17
#   #     STDFLAG: -std=c++2a
#   env:
#     CONAN_GCC_VERSIONS: 9
#     CONAN_REFERENCE: "icu/65.1"
#     CONAN_USERNAME: "kth"
#     CONAN_LOGIN_USERNAME: "fpelliccioni"
#     CONAN_CHANNEL: "stable"
#     CONAN_UPLOAD: "https://api.bintray.com/conan/k-nuth/kth"
#     CONAN_STABLE_BRANCH_PATTERN: "release/*"
#     CONAN_LOGIN_USERNAME: ENCRYPTED[!0fc5affed4d2084389c1cb0cfa369767e679a054d8e418dcf98c4d25d34b6bec6a5e3dd0235f3dd66686c1739d7bfbcc!]
#     CONAN_PASSWORD: ENCRYPTED[!3ed4d8bb7c72f35dc679f44fa521616f928c7286fa0d84195c3b1cd7c058e0154085f9b8dd8e57268c4e7a343eb34a18!]

#   # version_script: make -C test showcxxversion
#   install_script:
#     - apt-get update 
#     - apt-get install -f -y python2.7-dev
#     - wget https://bootstrap.pypa.io/get-pip.py 
#     - python get-pip.py 
#     - chmod +x .travis/install.sh 
#     - chmod +x .travis/run.sh 
#     - ./.travis/install.sh

#   build_script:
#     - ./.travis/run.sh

