#
# Copyright (c) 2016-2019 Knuth Project.
#
# This file is part of Knuth Project.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

env:
   global:
     - CONAN_REFERENCE: "icu/64.2"
     - CONAN_USERNAME: "kth"
     - CONAN_LOGIN_USERNAME: "fpelliccioni"
     - CONAN_CHANNEL: "stable"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/k-nuth/kth"

linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker

osx: &osx
   os: osx
   language: generic

matrix:
   include:

      # Linux, GCC, libstdc++ ------------------------------------------------------
      - <<: *linux
        env: CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/gcc9

      - <<: *linux
        env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8

      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7

      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=conanio/gcc6

      - <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=conanio/gcc5

      # - <<: *linux
      #   env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=conanio/gcc49

      # Linux, Clang, libstdc++ ----------------------------------------------------
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=7.0 CONAN_DOCKER_IMAGE=conanio/clang7

      - <<: *linux
        env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=conanio/clang60

      - <<: *linux
        env: CONAN_CLANG_VERSIONS=5.0 CONAN_DOCKER_IMAGE=conanio/clang50

      # - <<: *linux
      #   env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=conanio/clang40

      # - <<: *linux
      #   env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=conanio/clang39
        

      # macOS, apple-Clang, libc++ -------------------------------------------------

      - <<: *osx
        osx_image: xcode10.1
        env: CONAN_APPLE_CLANG_VERSIONS=10.0

      - <<: *osx
        osx_image: xcode9.3
        env: CONAN_APPLE_CLANG_VERSIONS=9.1


      # - <<: *osx
      #   osx_image: xcode9
      #   env: CONAN_APPLE_CLANG_VERSIONS=9.0

      # - <<: *osx
      #   osx_image: xcode8.3
      #   env: CONAN_APPLE_CLANG_VERSIONS=8.1

      # - <<: *osx
      #   osx_image: xcode7.3
      #   env: CONAN_APPLE_CLANG_VERSIONS=7.3
      # - <<: *osx
      #   osx_image: xcode8.2
      #   env: CONAN_APPLE_CLANG_VERSIONS=8.0
      

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - export CONAN_PRINT_RUN_COMMANDS=TRUE
  - export CONAN_LOGGING_LEVEL=10
  - chmod +x .travis/run.sh
  - ./.travis/run.sh

